"""Unified CLI for the Market Price Simulator & Liquidation Engine.

Examples:
    python cli.py --marginal-revenue --product MELON --quantity 50
    python cli.py --recovery-time --product STRAWBERRY --dump-size 40 --shops 2
    python cli.py --simulate-pvp --p0-order "SELL MELON 50" --p1-order "SELL MELON 10"
    python cli.py --generate-all-plots --output results/plots/
"""
import argparse
import json
import os

import marginal_revenue_analyzer as mra
import recovery_simulator as rec
import concurrent_order_simulator as cos
import visualizer as viz
from price_curve_engine import I0, MARKET_PARAMS


def _print_json(obj):
    print(json.dumps(obj, indent=2, default=float))


def cmd_marginal_revenue(args):
    res = mra.simulate_sale_path(args.product, args.initial_inv, args.quantity)
    print(f"{args.product}: selling {args.quantity} units from inv {res['initial_inventory']}")
    print(f"  spot quote:        ${mra.compute_price(args.product, args.initial_inv)}")
    print(f"  total revenue:     ${res['total_revenue']}")
    print(f"  avg realized:      ${res['avg_realized_price']:.2f}")
    print(f"  units frozen @$1:  {res['quantity'] - res['units_added_to_market']}")
    opt = mra.find_optimal_batch_size(args.product, args.initial_inv,
                                      args.min_price)
    print(f"optimal batch @ >= ${args.min_price}: Q*={opt['optimal_quantity']} "
          f"(revenue ${opt['total_revenue']}, avg ${opt['avg_realized_price']:.2f})")
    if args.show_mr:
        mr = res["unit_prices"]
        print("MR series (first 50):", mr[:50])


def cmd_recovery_time(args):
    shops = rec.worst_case_shops(args.product, args.shops) if args.shops else []
    res = rec.simulate_recovery(args.product, args.dump_size, shops=shops,
                                days=args.days)
    print(f"{args.product}: dump {args.dump_size} units | shops={shops or ['none']} "
          f"| drain {res['drain_per_day']}/day ({res['drain_per_day'] * rec.TURNS_PER_DAY} turns/day)")
    eff_note = "" if res["effective_dump_added"] == args.dump_size else \
        f" (only {res['effective_dump_added']} entered market; rest froze at $1)"
    print(f"immediate revenue: ${res['immediate_revenue']}{eff_note}")
    print(f"days to regain 50% of base (${res['base_price']}): {res['days_to_50pct_of_base']}")
    print(f"days to regain 90% of base: {res['days_to_90pct_of_base']}")
    print("trajectory (day, inventory, price):")
    for d, i, p in zip(res["traj_day"][:args.days + 1], res["traj_inventory"], res["traj_price"]):
        print(f"  day {d:>2}  inv {i:>9.0f}  ${p}")
    hold = rec.holding_ev(args.product, args.dump_size, shops=shops,
                          drip_days=args.drip_days)
    print(f"\nHolding EV: sell-now ${hold['sell_now_revenue']} vs "
          f"drip-{args.drip_days}d ${hold['drip_revenue']} -> {hold['recommendation']} "
          f"(delta ${hold['delta_drip_minus_now']})")


def cmd_simulate_pvp(args):
    p0 = [args.p0_order] if args.p0_order else []
    p1 = [args.p1_order] if args.p1_order else []
    res = cos.simulate_concurrent(p0, p1, trace=args.trace)
    print(json.dumps({k: v for k, v in res.items() if k != "trace"},
                     indent=2, default=float))
    if args.trace:
        print("\nexecution trace:")
        for e in res["trace"]:
            print(f"  {e['player']} {e['product']} @inv {e['inventory_before']:.0f} -> ${e['price']}")
    product = (p0 or p1)[0].split()[1]
    spoiler = cos.spoiler_attack(product, 50, 10)
    print(f"\nspoiler reference (opp sells 50, you spoil 10): damage=${spoiler['damage_to_opponent']} "
          f"my rev=${spoiler['my_revenue']}")


def generate_liquidation_guide(path):
    """Comprehensive markdown report: optimal sell batches per commodity."""
    lines = [
        "# Kaggriculture Liquidation Guide",
        "",
        "Generated by `simulations/price_simulator`. Execution is modeled one",
        "unit at a time with the $1-floor freeze rule. Batches start from an",
        "equilibrium market (inventory = I0 = 10,000).",
        "",
        "| Product | Base | Spot@I0 | Q* >= 75% base | Q* >= 50% base | "
        "Q* >= $5 | Units to floor from I0 |",
        "|---|---|---|---|---|---|---|",
    ]
    for prod, p in MARKET_PARAMS.items():
        b = p["base"]
        q75 = mra.find_optimal_batch_size(prod, I0, int(b * 0.75))["optimal_quantity"]
        q50 = mra.find_optimal_batch_size(prod, I0, int(b * 0.50))["optimal_quantity"]
        q5 = mra.find_optimal_batch_size(prod, I0, 5)["optimal_quantity"]
        fd = mra.floor_distance(prod)
        lines.append(
            f"| {prod} | ${b} | ${b} | {q75} | {q50} | {q5} | {fd:,} |")
    lines += [
        "",
        "## Slippage reference (dumping into equilibrium)",
        "",
        "| Product | " + " | ".join(f"Q={s}" for s in (1, 5, 10, 20, 50, 100)) + " |",
        "|" + "---|" * 8,
    ]
    for prod in MARKET_PARAMS:
        rows = mra.slippage_table(prod, I0)
        lines.append(
            f"| {prod} | " + " | ".join(f"${r['avg_realized_price']:.2f}" for r in rows) + " |")
    lines += [
        "",
        "## Reading this table",
        "",
        "- **Q\\* thresholds**: max units you can liquidate in one burst while",
        "  keeping every unit's executed price above the stated fraction of base.",
        "- Premium goods (MELON, STRAWBERRY, MILK, WOOL) have brutal glut curves:",
        "  their floor distance is tiny relative to staples — slice large sales",
        "  across days and let town drain absorb your footprint.",
        "- Staples (WHEAT, EGG) use log glut curves and absorb oversupply gently;",
        "  dumping hundreds of units costs only a few % of spot.",
        "- Selling into a $1 quote freezes inventory: those units are 'free' —",
        "  they do not deepen the glut further.",
    ]
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"liquidation guide written to {path}")


def main():
    ap = argparse.ArgumentParser(description="Kaggriculture price simulator & liquidation engine")
    ap.add_argument("--marginal-revenue", action="store_true")
    ap.add_argument("--recovery-time", action="store_true")
    ap.add_argument("--simulate-pvp", action="store_true")
    ap.add_argument("--generate-all-plots", action="store_true")
    ap.add_argument("--liquidation-guide", metavar="PATH", nargs="?", const="results/liquidation_guide.md")
    ap.add_argument("--product", type=str, default="MELON", choices=list(MARKET_PARAMS))
    ap.add_argument("--quantity", type=int, default=50)
    ap.add_argument("--initial-inv", type=int, default=I0)
    ap.add_argument("--min-price", type=int, default=None,
                    help="threshold for optimal batch sizing (default: 75%% of base)")
    ap.add_argument("--dump-size", type=int, default=40)
    ap.add_argument("--shops", type=int, default=2)
    ap.add_argument("--days", type=int, default=14)
    ap.add_argument("--drip-days", type=int, default=5)
    ap.add_argument("--p0-order", type=str, default="SELL MELON 50")
    ap.add_argument("--p1-order", type=str, default="SELL MELON 10")
    ap.add_argument("--output", type=str, default="results/plots/")
    ap.add_argument("--show-mr", action="store_true")
    ap.add_argument("--trace", action="store_true")
    args = ap.parse_args()

    if args.min_price is None:
        args.min_price = int(MARKET_PARAMS[args.product]["base"] * 0.75)

    did = False
    if args.marginal_revenue:
        cmd_marginal_revenue(args); did = True
    if args.recovery_time:
        cmd_recovery_time(args); did = True
    if args.simulate_pvp:
        cmd_simulate_pvp(args); did = True
    if args.generate_all_plots:
        files = viz.generate_all_plots(args.output)
        print(f"plots written to {args.output}: {files}"); did = True
    if args.liquidation_guide:
        generate_liquidation_guide(args.liquidation_guide); did = True
    if not did:
        ap.print_help()


if __name__ == "__main__":
    main()
