"""Persistent Whole-Farm Plan and Strategic State Machine.

Part of the SW-First Forward Architecture Redesign (Phase A).
Maintains cross-turn strategic state across an episode, tracking:
- Farm-wide strategic expansion state (observation-driven transitions)
- Commitment lifecycle stages (PROPOSED -> RESERVED -> ORDERED -> EXECUTED -> OBSERVED -> SETTLED)
- Target SW purchase window (nominal D8, window D7-D10)
- Tranche ramp progression (~8 -> ~16 -> ~20-24 tiles)
- Strict non-frivolous cancellation semantics (DOWNSIZE/DELAY/REPAIR preferred over CANCEL)
"""
from __future__ import annotations

import copy
import sys
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Set, Tuple

# Bidirectional module aliasing to guarantee singleton state across import paths
_mod_name = __name__
if _mod_name.startswith("agent."):
    _bare_name = _mod_name[6:]
    sys.modules.setdefault(_bare_name, sys.modules[_mod_name])
    _pkg_parts = _bare_name.split(".")
    if len(_pkg_parts) > 1 and _pkg_parts[0] in sys.modules:
        setattr(sys.modules[_pkg_parts[0]], _pkg_parts[1], sys.modules[_mod_name])
else:
    _agent_name = f"agent.{_mod_name}"
    sys.modules.setdefault(_agent_name, sys.modules[_mod_name])
    _pkg_parts = _mod_name.split(".")
    _agent_pkg = f"agent.{_pkg_parts[0]}"
    if "agent" in sys.modules:
        if _agent_pkg not in sys.modules and _pkg_parts[0] in sys.modules:
            sys.modules[_agent_pkg] = sys.modules[_pkg_parts[0]]
        if _agent_pkg in sys.modules:
            setattr(sys.modules[_agent_pkg], _pkg_parts[1], sys.modules[_mod_name])
            setattr(sys.modules["agent"], _pkg_parts[0], sys.modules[_agent_pkg])


class StrategicState(str, Enum):
    """High-level strategic progression of the whole farm."""
    SW_NOT_COMMITTED = "SW_NOT_COMMITTED"          # D0-D4: initial bootstrap, core farm establishment
    SW_PREPARING = "SW_PREPARING"                  # D4-D7: protecting dated liquidity, seed escrow, labor ramp
    SW_READY = "SW_READY"                          # D7-D10: target purchase window, commitments certified
    SW_PURCHASED = "SW_PURCHASED"                  # Observed engine unlock of SW land
    SW_RAMPING = "SW_RAMPING"                      # Rapid 2-4 day tranche progression (~8 -> ~16 -> ~20-24)
    THREE_QUADRANT_OPERATION = "THREE_QUADRANT_OPERATION"  # Mature commercial operation across NW + NE + SW
    SW_DOWNSIZED = "SW_DOWNSIZED"                  # Scaled back tranche size to preserve farm solvency
    SW_CANCELLED = "SW_CANCELLED"                  # Strictly constrained cancellation on irrecoverable hard failure


class CommitmentStatus(str, Enum):
    """Formal lifecycle of resource/asset commitments."""
    PROPOSED = "PROPOSED"    # Candidate generated by planner
    RESERVED = "RESERVED"    # Budget/labor/feed allocated in ledger
    ORDERED = "ORDERED"      # Market or unit action emitted
    EXECUTED = "EXECUTED"    # Engine processed action this turn
    OBSERVED = "OBSERVED"    # State fact confirmed in subsequent observation
    SETTLED = "SETTLED"      # Financial/physical cycle complete


@dataclass
class ExpansionTarget:
    """Strategic SW acquisition target parameters."""
    target_day: int = 8                    # Nominal strategic target day (Crop Dusta D8-9 pattern)
    earliest_feasible_day: int = 7         # Earliest viable window if capital allows
    latest_useful_day: int = 14            # Beyond D14, multi-harvest crops cannot complete lifecycle
    purchase_window: Tuple[int, int] = (7, 10)
    confidence: float = 1.0
    reason: str = "Initial strategic schedule"


@dataclass
class TrancheTarget:
    """Rapid expansion tranche specification."""
    tranche_id: int                        # 1, 2, 3
    target_tile_count: int                 # 8, 16, 24 cumulative
    max_ramp_days: int = 4                 # Complete full ramp in 2-4 days post-purchase
    active_tiles: List[Tuple[int, int]] = field(default_factory=list)
    status: CommitmentStatus = CommitmentStatus.PROPOSED


@dataclass
class FarmPlan:
    """Persistent strategic plan object surviving across turns within an episode."""
    state: StrategicState = StrategicState.SW_NOT_COMMITTED
    expansion_target: ExpansionTarget = field(default_factory=ExpansionTarget)
    current_tranche: int = 0               # 0 (none), 1 (~8), 2 (~16), 3 (~24)
    target_tranches: List[TrancheTarget] = field(default_factory=lambda: [
        TrancheTarget(tranche_id=1, target_tile_count=8),
        TrancheTarget(tranche_id=2, target_tile_count=16),
        TrancheTarget(tranche_id=3, target_tile_count=24),
    ])
    observed_sw_unlocked: bool = False
    observed_sw_tiles_developed: int = 0
    cancellation_reason: Optional[str] = None
    state_history: List[Dict[str, Any]] = field(default_factory=list)
    step: int = 0
    day: int = 0
    hour: int = 0

    def record_transition(self, new_state: StrategicState, reason: str) -> None:
        """Record an explicit, observation-justified state transition."""
        prev = self.state
        self.state = new_state
        self.state_history.append({
            "step": self.step,
            "day": self.day,
            "hour": self.hour,
            "from_state": prev.value,
            "to_state": new_state.value,
            "reason": reason,
        })

    def update_from_observation(self, ctx: Dict[str, Any]) -> None:
        """Update strategic state strictly from engine-observed facts.

        Transitions occur from OBSERVED facts, not emitted intents.
        """
        self.step = ctx.get("step", 0)
        self.day = ctx.get("day", 0)
        self.hour = ctx.get("hour", 0)

        farm = ctx.get("farm")
        if farm is None:
            return

        unlocked = set(getattr(farm, "unlocked", []))
        # SW quadrant corresponds to quadrant 3 / SW coordinate range (x < 5, y >= 5)
        sw_unlocked = ("SW" in unlocked) or (3 in unlocked) or (len(unlocked) >= 3)
        self.observed_sw_unlocked = sw_unlocked

        # Count active SW development
        developed_count = 0
        for t in farm.iter_tiles():
            x = getattr(t, "x", t.pos[0] if hasattr(t, "pos") else 0)
            y = getattr(t, "y", t.pos[1] if hasattr(t, "pos") else 0)
            # SW quadrant is x in [0, 4], y in [5, 9] excluding shed access
            if 0 <= x < 5 and 5 <= y < 10:
                if (x, y) not in [(4, 4), (5, 4), (4, 5), (5, 5)]:
                    kind = getattr(t, "kind", None)
                    if kind in ("PLANT", "PASTURE", "COOP") or getattr(t, "is_plant", False) or getattr(t, "is_animal", False):
                        developed_count += 1
        self.observed_sw_tiles_developed = developed_count

        # --- Observation-Driven State Machine Transitions ---
        if self.state == StrategicState.SW_CANCELLED:
            # Cancellation is terminal for SW development
            return

        if sw_unlocked:
            if self.state in (StrategicState.SW_NOT_COMMITTED, StrategicState.SW_PREPARING, StrategicState.SW_READY):
                self.record_transition(
                    StrategicState.SW_PURCHASED,
                    reason=f"Observed engine quadrant unlock at Day {self.day} Hour {self.hour}"
                )

            if self.state == StrategicState.SW_PURCHASED:
                if developed_count >= 4:
                    self.current_tranche = 1
                    self.record_transition(
                        StrategicState.SW_RAMPING,
                        reason=f"Observed {developed_count} developed SW tiles; entered RAMPING"
                    )

            elif self.state == StrategicState.SW_RAMPING:
                if developed_count >= 14:
                    self.current_tranche = 2
                if developed_count >= 20:
                    self.current_tranche = 3
                    self.record_transition(
                        StrategicState.THREE_QUADRANT_OPERATION,
                        reason=f"Observed {developed_count} developed SW tiles; reached mature THREE_QUADRANT_OPERATION"
                    )

        else:
            # Pre-purchase strategic states
            if self.state == StrategicState.SW_NOT_COMMITTED:
                if self.day >= 4:
                    self.record_transition(
                        StrategicState.SW_PREPARING,
                        reason=f"Reached Day {self.day} (>= 4); beginning explicit SW preparation"
                    )

            elif self.state == StrategicState.SW_PREPARING:
                if self.day >= self.expansion_target.earliest_feasible_day:
                    self.record_transition(
                        StrategicState.SW_READY,
                        reason=f"Reached Day {self.day} (target window {self.expansion_target.purchase_window})"
                    )

            elif self.state == StrategicState.SW_READY:
                # Check for strict, non-frivolous cancellation conditions
                can_cancel, cancel_reason = self.evaluate_cancellation_criteria(ctx)
                if can_cancel:
                    self.cancellation_reason = cancel_reason
                    self.record_transition(StrategicState.SW_CANCELLED, reason=cancel_reason)

    def evaluate_cancellation_criteria(self, ctx: Dict[str, Any]) -> Tuple[bool, str]:
        """Check whether strict conditions for SW cancellation are met.

        CANCEL is permitted ONLY IF:
        1. Day > latest_useful_day (e.g. Day 14+ where crops cannot harvest)
        2. No feasible SW tranche exists after ALL lower-value discretionary commitments removed
        3. Hard feed/cash insolvency is unrepairable.

        Downsizing or delaying MUST be preferred over cancelling.
        """
        if self.day > self.expansion_target.latest_useful_day:
            return True, f"Day {self.day} exceeds latest useful SW purchase deadline (Day {self.expansion_target.latest_useful_day})"

        farm = ctx.get("farm")
        money = float(getattr(farm, "money", 0)) if farm else 0.0

        # Hard insolvency: cash < $500 on D12+ with zero prospective revenue
        if self.day >= 12 and money < 500:
            return True, f"Severe cash depletion (${money:.1f}) on Day {self.day} makes land acquisition infeasible"

        return False, ""

    def request_downsize(self, reason: str) -> None:
        """Scale down expansion tranche to preserve core solvency."""
        if self.state in (StrategicState.SW_READY, StrategicState.SW_RAMPING):
            self.record_transition(StrategicState.SW_DOWNSIZED, reason=reason)

    def snapshot(self) -> Dict[str, Any]:
        """Return an immutable deep-copy snapshot for telemetry or analysis."""
        return {
            "state": self.state.value,
            "step": self.step,
            "day": self.day,
            "hour": self.hour,
            "target_day": self.expansion_target.target_day,
            "current_tranche": self.current_tranche,
            "observed_sw_unlocked": self.observed_sw_unlocked,
            "observed_sw_tiles_developed": self.observed_sw_tiles_developed,
            "cancellation_reason": self.cancellation_reason,
            "history_length": len(self.state_history),
        }


# Module singleton for turn-to-turn persistence within a game
_PERSISTENT_FARM_PLAN: Optional[FarmPlan] = None


def get_farm_plan() -> FarmPlan:
    """Return the persistent FarmPlan instance for the current episode."""
    global _PERSISTENT_FARM_PLAN
    if _PERSISTENT_FARM_PLAN is None:
        _PERSISTENT_FARM_PLAN = FarmPlan()
    return _PERSISTENT_FARM_PLAN


def reset_farm_plan() -> None:
    """Hard-reset the persistent FarmPlan between matches across all aliases."""
    global _PERSISTENT_FARM_PLAN
    _PERSISTENT_FARM_PLAN = FarmPlan()
    for k in ("strategy.farm_plan", "agent.strategy.farm_plan"):
        mod = sys.modules.get(k)
        if mod is not None and mod is not sys.modules.get(__name__) and hasattr(mod, "_PERSISTENT_FARM_PLAN"):
            mod._PERSISTENT_FARM_PLAN = _PERSISTENT_FARM_PLAN
